"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "da" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  da: {
    // Common
    "common.loading": "Indlæser...",
    "common.error": "Fejl",
    "common.success": "Succes",
    "common.cancel": "Annuller",
    "common.save": "Gem",
    "common.delete": "Slet",
    "common.edit": "Rediger",
    "common.create": "Opret",
    "common.creating": "Opretter...",
    "common.back": "Tilbage",
    "common.next": "Næste",
    "common.previous": "Forrige",
    "common.close": "Luk",
    "common.yes": "Ja",
    "common.no": "Nej",
    "common.confirm": "Bekræft",
    "common.search": "Søg",
    "common.filter": "Filtrer",
    "common.sort": "Sorter",
    "common.refresh": "Opdater",
    "common.user": "Bruger",
    "common.guest": "Gæst",
    "common.footballGame": "Fodbold spil",
    
    // Dashboard
    "dashboard.managerHub": "Manager Hub",
    "dashboard.welcomeBack": "Velkommen tilbage",
    "dashboard.wins": "Sejre",
    "dashboard.activeLeagues": "Aktive ligaer",
    "dashboard.totalLeagues": "Totale ligaer",
    "dashboard.winRate": "Vindrate",
    "dashboard.victoryInPremierLeague": "Sejr i Premier League",
    "dashboard.hoursAgo": "timer siden",
    "dashboard.draftedMessi": "Draftede Messi",
    "dashboard.daysAgo": "dage siden",
    "dashboard.joinedChampionsLeague": "Deltog i Champions League",
    "dashboard.unlockedDraftMaster": "Låste op for Draft Master",
    "dashboard.weekAgo": "uge siden",
    "dashboard.championsLeagueDraft": "Champions League Draft",
    "dashboard.tomorrow": "I morgen",
    "dashboard.premierLeagueMatchDay": "Premier League Kampdag",
    "dashboard.friday": "Fredag",
    "dashboard.transferWindowOpens": "Transfervindue åbner",
    "dashboard.nextMonday": "Næste mandag",
    "dashboard.quickActions": "Hurtige handlinger",
    "dashboard.jumpIntoAction": "Hop i gang med handling",
    "dashboard.myLeagues": "Mine Ligaer",
    "dashboard.findLeagues": "Find Ligaer",
    "dashboard.createLeague": "Opret Liga",
    "dashboard.leaderboard": "Rangliste",
    "dashboard.recentActivity": "Seneste Aktivitet",
    "dashboard.latestAchievements": "Dine seneste præstationer og handlinger",
    "dashboard.upcomingEvents": "Kommende Begivenheder",
    "dashboard.dontMissDates": "Gå ikke glip af disse vigtige datoer",
    
    // Navigation
    "nav.managerHub": "Manager Hub",
    "nav.competitions": "Konkurrencer",
    "nav.myLeagues": "Mine Ligaer",
    "nav.scoutLeagues": "Spejde Ligaer",
    "nav.administration": "Administration",
    "nav.createLeague": "Opret Liga",
    "nav.rankings": "Rangliste",
    "nav.user": "Bruger",
    
    // Account
    "account.language": "Sprog",
    "account.account": "Konto",
    
    // League Creation Modal
    "league.createNewLeague": "Opret Ny Liga",
    "league.setupNewLeague": "Opret en ny liga og inviter dine venner til at deltage",
    "league.leagueName": "Liga Navn",
    "league.enterLeagueName": "Indtast liga navn",
    "league.description": "Beskrivelse (Valgfrit)",
    "league.enterDescription": "Indtast liga beskrivelse",
    "league.maximumTeams": "Maksimale Hold",
    "league.draftMethod": "Draft Metode",
    "league.snakeDraft": "Snake Draft",
    "league.signupDeadline": "Tilmelding Deadline",
    "league.dateFormat": "dd.mm.åååå, --.--",
    "league.createLeague": "Opret Liga",
    
    // League Pages
    "leagues.myCompetitions": "Mine konkurrencer",
    "leagues.manageLeagues": "Administrer dine ligaer og følg",
    "leagues.myLeagues": "Mine Ligaer",
    "leagues.totalLeagues": "Totale ligaer",
    "leagues.active": "Aktive",
    "leagues.upcomingDrafts": "Kommende drafts",
    "leagues.totalWins": "Totale sejre",
    "leagues.noLeaguesYet": "Ingen Ligaer Endnu",
    "leagues.createFirstLeague": "Opret din første liga",
    "leagues.createYourFirstLeague": "Opret Din Første Liga",
    "leagues.createNewLeague": "Opret Ny Liga",
    
    // Home
    "home.subtitle": "Den ultimative fantasy fodbold draft oplevelse. Opret ligaer, draft spillere, og konkurrer med venner.",
    "home.getStarted": "Kom i gang",
    "home.activePlayers": "Aktive spillere",
    "home.leaguesCreated": "Ligaer oprettet",
    "home.draftsCompleted": "Drafts gennemført",
    "home.whyChoose": "Hvorfor vælge Draft Manager?",
    "home.experienceAdvanced": "Oplev den mest avancerede fantasy fodbold draft platform med banebrydende funktioner.",
    "home.competitiveLeagues": "Konkurrencedygtige ligaer",
    "home.competitiveLeaguesDesc": "Deltag i eller opret ligaer med venner og konkurrer i snake eller lineære draft formater. Følg din fremskridt og klatr på ranglisten.",
    "home.teamManagement": "Hold administration",
    "home.teamManagementDesc": "Byg dit drømmehold med rigtige spillere fra top ligaer. Administrer din trup og træf strategiske beslutninger gennem sæsonen.",
    "home.realTimeDrafts": "Real-time drafts",
    "home.realTimeDraftsDesc": "Oplev live draft sessioner med real-time opdateringer og notifikationer. Gå aldrig glip af et valg med vores avancerede draft system.",
    "home.advancedAnalytics": "Avancerede analyser",
    "home.advancedAnalyticsDesc": "Få detaljerede statistikker og indsigter om dine spillere og hold. Træf datadrevne beslutninger for at maksimere din succes.",
    "home.securePlatform": "Sikker platform",
    "home.securePlatformDesc": "Din data og sikkerhed er vores prioritet. Vi bruger branchens bedste sikkerhedspraksis for at beskytte din information.",
    "home.mobileOptimized": "Mobil optimeret",
    "home.mobileOptimizedDesc": "Administrer dine ligaer og hold på farten med vores fuldt responsive design. Fungerer perfekt på alle enheder.",
    "home.globalCommunity": "Globalt fællesskab",
    "home.globalCommunityDesc": "Forbind med fantasy fodbold entusiaster verden over. Del strategier, diskuter spillere, og byg varige venskaber.",
    "home.howItWorks": "Sådan fungerer det",
    "home.howItWorksDesc": "Kom i gang på bare få simple trin og begynd din fantasy fodbold rejse.",
    "home.createAccount": "Opret konto",
    "home.createAccountDesc": "Tilmeld dig gratis og opsæt din profil. Det tager mindre end 2 minutter at komme i gang.",
    "home.joinOrCreateLeague": "Deltag i eller opret liga",
    "home.joinOrCreateLeagueDesc": "Gennemse eksisterende ligaer eller opret din egen. Inviter venner og opsæt dine draft præferencer.",
    "home.draftAndCompete": "Draft og konkurrer",
    "home.draftAndCompeteDesc": "Deltag i live drafts, administrer dit hold, og konkurrer om mesterskabstitlen.",
    "home.readyToStart": "Klar til at begynde at draft?",
    "home.joinThousands": "Deltag med tusindvis af fantasy fodbold managere der stoler på Draft Manager til deres ligaer.",
    "home.startFreeTrial": "Start gratis prøveperiode",
    
    // Auth
    "auth.login": "Log ind",
    "auth.register": "Opret konto",
    "auth.logout": "Log ud",
    "auth.email": "E-mail",
    "auth.password": "Adgangskode",
    "auth.name": "Navn",
    "auth.confirmPassword": "Bekræft adgangskode",
    "auth.forgotPassword": "Glemt adgangskode?",
    "auth.rememberMe": "Husk mig",
    "auth.createAccount": "Opret konto",
    "auth.alreadyHaveAccount": "Har du allerede en konto?",
    "auth.dontHaveAccount": "Har du ikke en konto?",
    "auth.signIn": "Log ind",
    "auth.signUp": "Tilmeld dig",
    "auth.welcomeBack": "Velkommen tilbage",
    "auth.joinDraftManager": "Tilmeld dig Draft Manager og start din fantasy fodbold rejse",
    "auth.passwordMinLength": "Adgangskode skal være mindst 8 karakterer lang",
    "auth.agreeToTerms": "Jeg accepterer",
    "auth.termsOfService": "Servicevilkår",
    "auth.and": "og",
    "auth.privacyPolicy": "Privatlivspolitik",
    "auth.invalidCredentials": "Ugyldige legitimationsoplysninger",
    "auth.emailInUse": "E-mail er allerede i brug",
    "auth.registrationFailed": "Registrering mislykkedes",
    "auth.loginFailed": "Login mislykkedes",
    "auth.nameOptional": "Navn (valgfrit)",
    "auth.enterName": "Indtast dit navn",
    "auth.enterEmail": "Indtast din e-mail",
    "auth.createPassword": "Opret en adgangskode",
    "auth.pleaseAgreeToTerms": "Du skal acceptere Servicevilkår og Privatlivspolitik",
    "auth.enterValidEmail": "Indtast en gyldig e-mail adresse",
    "auth.loginToAccount": "Log ind på din Draft Manager konto",
    "auth.signingIn": "Logger ind...",
    "auth.creatingAccount": "Opretter konto...",
    
    // Dashboard
    "dashboard.managerHub": "Manager Hub",
    "dashboard.welcomeBack": "Velkommen tilbage",
    "dashboard.wins": "Sejre",
    "dashboard.activeLeagues": "Aktive ligaer",
    "dashboard.totalLeagues": "Totale ligaer",
    "dashboard.winRate": "Sejrsrate",
    "dashboard.quickActions": "Hurtige handlinger",
    "dashboard.jumpIntoAction": "Hop ind i handlingen",
    "dashboard.myLeagues": "Mine ligaer",
    "dashboard.findLeagues": "Find ligaer",
    "dashboard.createLeague": "Opret liga",
    "dashboard.leaderboard": "Rangliste",
    "dashboard.victoryInPremierLeague": "Sejr i Premier League mesterskab",
    "dashboard.draftedMessi": "Draftede Messi i Fantasy League",
    "dashboard.joinedChampionsLeague": "Deltog i Champions League",
    "dashboard.unlockedDraftMaster": "Låste 'Draft Master' præstation op",
    "dashboard.championsLeagueDraft": "Champions League Draft",
    "dashboard.premierLeagueMatchDay": "Premier League kampdag",
    "dashboard.transferWindowOpens": "Transfer vindue åbner",
    "dashboard.tomorrow": "I morgen",
    "dashboard.friday": "Fredag",
    "dashboard.nextMonday": "Næste mandag",
    "dashboard.hoursAgo": "timer siden",
    "dashboard.daysAgo": "dage siden",
    "dashboard.weekAgo": "uge siden",
    
    // Leagues
    "leagues.myCompetitions": "Mine konkurrencer",
    "leagues.manageLeagues": "Administrer dine ligaer og følg din fremskridt",
    "leagues.totalLeagues": "Totale ligaer",
    "leagues.active": "Aktive",
    "leagues.upcomingDrafts": "Kommende drafts",
    "leagues.totalWins": "Totale sejre",
    "leagues.myLeagues": "Mine Ligaer",
    "leagues.createNewLeague": "Opret Ny Liga",
    "leagues.noLeaguesYet": "Ingen Ligaer Endnu",
    "leagues.createFirstLeague": "Opret din første liga eller deltag i en eksisterende for at komme i gang.",
    "leagues.createYourFirstLeague": "Opret Din Første Liga",
    "leagues.teams": "Hold",
    "leagues.method": "Metode",
    "leagues.deadline": "Deadline",
    "leagues.top3": "Top 3",
    "leagues.nextEvent": "Næste Begivenhed",
    "leagues.viewDetails": "Se Detaljer",
    "leagues.joinLeague": "Deltag i Liga",
    "leagues.leaveLeague": "Forlad Liga",
    "leagues.createTeam": "Opret Hold",
    "leagues.draftDay": "Draft Dag",
    "leagues.draftBegins": "Draft Begynder",
    "leagues.matchDay": "Kamp Dag",
    "leagues.finalDraftPreparation": "Sidste draft forberedelse",
    "leagues.liveDraftSession": "Live draft session",
    "leagues.tomorrow": "I morgen",
    "leagues.today": "I dag",
    "leagues.friday": "Fredag",
    
    // Browse Leagues
    "browseLeagues.title": "Liga spejderi",
    "browseLeagues.subtitle": "Opdag og deltag i de bedste konkurrencer",
    "browseLeagues.availableLeagues": "Tilgængelige ligaer",
    "browseLeagues.scoutLeagues": "Spejd ligaer efter navn eller beskrivelse...",
    "browseLeagues.filterByStatus": "Filtrer efter status",
    "browseLeagues.sortByPopularity": "Sorter efter popularitet",
    "browseLeagues.noLeaguesDiscovered": "Ingen ligaer opdaget",
    "browseLeagues.noLeaguesMatch": "Ingen ligaer matcher dine spejder kriterier for",
    "browseLeagues.noPublicLeagues": "Ingen offentlige ligaer er tilgængelige for spejderi i øjeblikket.",
    "browseLeagues.clearSearch": "Ryd søgning",
    "browseLeagues.scoutedLeagues": "Spejdede ligaer",
    "browseLeagues.clickToJoin": "Klik på en liga for at deltage i konkurrencen",
    "browseLeagues.scoutingLeagues": "Spejder ligaer...",
    "browseLeagues.findingBestDraft": "Finder de bedste draft muligheder til dig",
    
    // 404 Not Found
    "notFound.pageNotFound": "Side ikke fundet",
    "notFound.pageNotFoundDesc": "Siden du leder efter eksisterer ikke eller er blevet flyttet.",
    "notFound.goHome": "Gå hjem",
    "notFound.goBack": "Gå tilbage",
    
    // Navigation
    "navigation.dashboard": "Dashboard",
    "navigation.leagues": "Ligaer",
    "navigation.teams": "Hold",
    "navigation.browseLeagues": "Gennemse ligaer",
    "navigation.account": "Konto",
    "navigation.profile": "Profil",
    "navigation.settings": "Indstillinger",
    "navigation.help": "Hjælp",
    "navigation.about": "Om",
    "navigation.managerHub": "Manager Hub",
    "navigation.myLeagues": "Mine Ligaer",
    "navigation.scoutLeagues": "Spejde Ligaer",
    "navigation.createLeague": "Opret Liga",
    "navigation.leaderboard": "Rangliste",
    "navigation.competitions": "Konkurrencer",
    "navigation.management": "Administration",
    
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.welcome": "Velkommen tilbage",
    "dashboard.overview": "Oversigt",
    "dashboard.recentActivity": "Seneste aktivitet",
    "dashboard.quickActions": "Hurtige handlinger",
    "dashboard.stats": "Statistikker",
    "dashboard.matches": "Kampe",
    "dashboard.wins": "Sejre",
    "dashboard.losses": "Nederlag",
    "dashboard.winRate": "Sejrsrate",
    "dashboard.points": "Point",
    "dashboard.rank": "Rang",
    "dashboard.level": "Niveau",
    "dashboard.experience": "Erfaring",
    "dashboard.nextLevel": "Næste niveau",
    "dashboard.totalMatches": "Samlede kampe",
    "dashboard.careerWinRate": "Karriere sejrsrate",
    
    // Leagues
    "leagues.title": "Ligaer",
    "leagues.myLeagues": "Mine Ligaer",
    "leagues.browseLeagues": "Gennemse Ligaer",
    "leagues.createLeague": "Opret Liga",
    "leagues.joinLeague": "Deltag i Liga",
    "leagues.leagueName": "Liga navn",
    "leagues.leagueDescription": "Liga beskrivelse",
    "leagues.maxPlayers": "Maks spillere",
    "leagues.entryFee": "Deltagelsesgebyr",
    "leagues.prizePool": "Præmiesum",
    "leagues.startDate": "Startdato",
    "leagues.endDate": "Slutdato",
    "leagues.status": "Status",
    "leagues.active": "Aktiv",
    "leagues.completed": "Afsluttet",
    "leagues.upcoming": "Kommende",
    "leagues.players": "Spillere",
    "leagues.owner": "Ejer",
    "leagues.created": "Oprettet",
    "leagues.joined": "Deltaget",
    "leagues.leave": "Forlad",
    "leagues.viewDetails": "Se detaljer",
    "leagues.noLeagues": "Ingen ligaer fundet",
    "leagues.createFirstLeague": "Opret din første liga",
    "leagues.joinFirstLeague": "Deltag i din første liga",
    
    // Teams
    "teams.title": "Hold",
    "teams.myTeam": "Mit Hold",
    "teams.teamName": "Hold navn",
    "teams.teamDescription": "Hold beskrivelse",
    "teams.formation": "Formation",
    "teams.captain": "Kaptajn",
    "teams.viceCaptain": "Vice-kaptajn",
    "teams.players": "Spillere",
    "teams.budget": "Budget",
    "teams.remainingBudget": "Resterende budget",
    "teams.totalValue": "Samlet værdi",
    "teams.avgRating": "Gennemsnitlig rating",
    "teams.chemistry": "Kemi",
    "teams.tactics": "Taktik",
    "teams.defensive": "Defensiv",
    "teams.offensive": "Offensiv",
    "teams.balanced": "Balanceret",
    "teams.aggressive": "Aggressiv",
    "teams.conservative": "Konservativ",
    
    // Account
    "account.title": "Konto",
    "account.profile": "Profil",
    "account.personalInfo": "Personlige oplysninger",
    "account.managerInfo": "Manager information",
    "account.security": "Sikkerhed",
    "account.preferences": "Præferencer",
    "account.language": "Sprog",
    "account.selectLanguage": "Vælg sprog",
    "account.danish": "Dansk",
    "account.english": "Engelsk",
    "account.theme": "Tema",
    "account.light": "Lys",
    "account.dark": "Mørk",
    "account.system": "System",
    "account.notifications": "Notifikationer",
    "account.emailNotifications": "E-mail notifikationer",
    "account.pushNotifications": "Push notifikationer",
    "account.changePassword": "Skift adgangskode",
    "account.currentPassword": "Nuværende adgangskode",
    "account.newPassword": "Ny adgangskode",
    "account.confirmNewPassword": "Bekræft ny adgangskode",
    "account.updateProfile": "Opdater profil",
    "account.updatePassword": "Opdater adgangskode",
    "account.deleteAccount": "Slet konto",
    "account.profileUpdated": "Profil opdateret",
    "account.passwordUpdated": "Adgangskode opdateret",
    "account.accountDeleted": "Konto slettet",
    "account.updatePersonalInfo": "Opdater dine personlige oplysninger og kontaktoplysninger",
    "account.updatePasswordSecure": "Opdater din adgangskode for at holde din konto sikker",
    "account.enterCurrentPassword": "Indtast din nuværende adgangskode",
    "account.enterNewPassword": "Indtast din nye adgangskode",
    "account.confirmNewPassword": "Bekræft din nye adgangskode",
    "account.updating": "Opdaterer...",
    "account.gameDataManagement": "Spil Data Administration",
    "account.resetGameData": "Nulstil spil data og fyld med eksempel ligaer til test",
    "account.warningResetData": "Advarsel: Dette vil slette al spil data",
    "account.resetDataDescription": "Dette vil slette alle nuværende ligaer, hold, og manager fremskridt, derefter fylde spillet med eksempel konkurrencer til test.",
    "account.resettingGameData": "Nulstiller spil data...",
    "account.resetGameDataLoadSample": "Nulstil spil data og indlæs eksempel ligaer",
    "account.managerProfile": "Manager Profil",
    "account.manageCareer": "Administrer din karriere og kontoindstillinger",
    "account.careerWinRate": "Karriere sejrsrate",
    "account.levelRank": "Niveau {level} - {rank}",
    "account.achievements": "Præstationer",
    "account.careerMilestones": "Dine karriere milepæle og præstationer",
    "account.firstVictory": "Første Sejr",
    "account.winFirstMatch": "Vind din første liga kamp",
    "account.draftMaster": "Draft Mester",
    "account.completeDrafts": "Fuldfør 10 succesfulde drafts",
    "account.leagueChampion": "Liga Mester",
    "account.winChampionship": "Vind en liga mesterskab",
    "account.perfectSeason": "Perfekt Sæson",
    "account.winAllMatches": "Vind alle kampe i en sæson",
    "account.wins": "Sejre",
    "account.losses": "Nederlag",
    "account.totalMatches": "Samlede kampe",
    "account.experience": "Erfaring",
    "account.level": "Niveau",
    "account.enterName": "Indtast dit navn",
    "account.enterEmail": "Indtast din e-mail",
    "account.noChangesToSave": "Ingen ændringer at gemme",
    "account.profileUpdatedSuccess": "Profil opdateret med succes!",
    "account.passwordUpdatedSuccess": "Adgangskode opdateret med succes!",
    "account.newPasswordsDoNotMatch": "Nye adgangskoder matcher ikke",
    "account.passwordTooShort": "Ny adgangskode skal være mindst 8 karakterer lang",
    "account.databaseSeededSuccess": "Database fyldt med succes! Du kan nu gennemse ligaer og se eksempel data.",
    "account.failedToSeedDatabase": "Kunne ikke fylde database",
    "account.failedToUpdateProfile": "Kunne ikke opdatere profil",
    "account.failedToUpdatePassword": "Kunne ikke opdatere adgangskode",
    
    // Errors
    "errors.generic": "Der opstod en fejl",
    "errors.network": "Netværksfejl",
    "errors.unauthorized": "Ikke autoriseret",
    "errors.forbidden": "Forbudt",
    "errors.notFound": "Ikke fundet",
    "errors.serverError": "Server fejl",
    "errors.validation": "Validerings fejl",
    "errors.required": "Dette felt er påkrævet",
    "errors.invalidEmail": "Ugyldig e-mail adresse",
    "errors.passwordTooShort": "Adgangskode er for kort",
    "errors.passwordsDoNotMatch": "Adgangskoder matcher ikke",
    "errors.userNotFound": "Bruger ikke fundet",
    "errors.emailAlreadyExists": "E-mail eksisterer allerede",
    "errors.invalidCredentials": "Ugyldige legitimationsoplysninger",
    "errors.accountLocked": "Konto er låst",
    "errors.accountDisabled": "Konto er deaktiveret",
    "errors.tokenExpired": "Token er udløbet",
    "errors.tokenInvalid": "Token er ugyldig",
    
    // Success
    "success.profileUpdated": "Profil opdateret med succes",
    "success.passwordChanged": "Adgangskode ændret med succes",
    "success.accountCreated": "Konto oprettet med succes",
    "success.loggedIn": "Logget ind med succes",
    "success.loggedOut": "Logget ud med succes",
    "success.leagueCreated": "Liga oprettet med succes",
    "success.leagueJoined": "Deltaget i liga med succes",
    "success.teamUpdated": "Hold opdateret med succes",
    "success.dataReset": "Data nulstillet med succes"
  },
  en: {
    // Common
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.create": "Create",
    "common.creating": "Creating...",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.close": "Close",
    "common.yes": "Yes",
    "common.no": "No",
    "common.confirm": "Confirm",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.refresh": "Refresh",
    "common.user": "User",
    "common.guest": "Guest",
    "common.footballGame": "Football Game",
    
    // Dashboard
    "dashboard.managerHub": "Manager Hub",
    "dashboard.welcomeBack": "Welcome back",
    "dashboard.wins": "Wins",
    "dashboard.activeLeagues": "Active leagues",
    "dashboard.totalLeagues": "Total leagues",
    "dashboard.winRate": "Win rate",
    "dashboard.victoryInPremierLeague": "Victory in Premier League",
    "dashboard.hoursAgo": "hours ago",
    "dashboard.draftedMessi": "Drafted Messi",
    "dashboard.daysAgo": "days ago",
    "dashboard.joinedChampionsLeague": "Joined Champions League",
    "dashboard.unlockedDraftMaster": "Unlocked Draft Master",
    "dashboard.weekAgo": "week ago",
    "dashboard.championsLeagueDraft": "Champions League Draft",
    "dashboard.tomorrow": "Tomorrow",
    "dashboard.premierLeagueMatchDay": "Premier League Match Day",
    "dashboard.friday": "Friday",
    "dashboard.transferWindowOpens": "Transfer window opens",
    "dashboard.nextMonday": "Next Monday",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.jumpIntoAction": "Jump into action",
    "dashboard.myLeagues": "My Leagues",
    "dashboard.findLeagues": "Find Leagues",
    "dashboard.createLeague": "Create League",
    "dashboard.leaderboard": "Leaderboard",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.latestAchievements": "Your latest achievements and actions",
    "dashboard.upcomingEvents": "Upcoming Events",
    "dashboard.dontMissDates": "Don't miss these important dates",
    
    // Navigation
    "nav.managerHub": "Manager Hub",
    "nav.competitions": "Competitions",
    "nav.myLeagues": "My Leagues",
    "nav.scoutLeagues": "Scout Leagues",
    "nav.administration": "Administration",
    "nav.createLeague": "Create League",
    "nav.rankings": "Rankings",
    "nav.user": "User",
    
    // Account
    "account.language": "Language",
    "account.account": "Account",
    
    // League Creation Modal
    "league.createNewLeague": "Create New League",
    "league.setupNewLeague": "Set up a new league and invite your friends to join",
    "league.leagueName": "League Name",
    "league.enterLeagueName": "Enter league name",
    "league.description": "Description (Optional)",
    "league.enterDescription": "Enter league description",
    "league.maximumTeams": "Maximum Teams",
    "league.draftMethod": "Draft Method",
    "league.snakeDraft": "Snake Draft",
    "league.signupDeadline": "Signup Deadline",
    "league.dateFormat": "dd.mm.yyyy, --:--",
    "league.createLeague": "Create League",
    
    // League Pages
    "leagues.myCompetitions": "My Competitions",
    "leagues.manageLeagues": "Manage your leagues and follow",
    "leagues.myLeagues": "My Leagues",
    "leagues.totalLeagues": "Total leagues",
    "leagues.active": "Active",
    "leagues.upcomingDrafts": "Upcoming drafts",
    "leagues.totalWins": "Total wins",
    "leagues.noLeaguesYet": "No Leagues Yet",
    "leagues.createFirstLeague": "Create your first league",
    "leagues.createYourFirstLeague": "Create Your First League",
    "leagues.createNewLeague": "Create New League",
    
    // Home
    "home.subtitle": "The ultimate fantasy football draft experience. Create leagues, draft players, and compete with friends.",
    "home.getStarted": "Get Started",
    "home.activePlayers": "Active Players",
    "home.leaguesCreated": "Leagues Created",
    "home.draftsCompleted": "Drafts completed",
    "home.whyChoose": "Why Choose Draft Manager?",
    "home.experienceAdvanced": "Experience the most advanced fantasy football draft platform with cutting-edge features.",
    "home.competitiveLeagues": "Competitive Leagues",
    "home.competitiveLeaguesDesc": "Join or create leagues with friends and compete in snake or linear draft formats. Track your progress and climb the leaderboards.",
    "home.teamManagement": "Team Management",
    "home.teamManagementDesc": "Build your dream team with real players from top leagues. Manage your roster and make strategic decisions throughout the season.",
    "home.realTimeDrafts": "Real-time Drafts",
    "home.realTimeDraftsDesc": "Experience live draft sessions with real-time updates and notifications. Never miss a pick with our advanced draft system.",
    "home.advancedAnalytics": "Advanced Analytics",
    "home.advancedAnalyticsDesc": "Get detailed statistics and insights about your players and teams. Make data-driven decisions to maximize your success.",
    "home.securePlatform": "Secure Platform",
    "home.securePlatformDesc": "Your data and security are our priority. We use industry-leading security practices to protect your information.",
    "home.mobileOptimized": "Mobile Optimized",
    "home.mobileOptimizedDesc": "Manage your leagues and teams on the go with our fully responsive design. Works perfectly on all devices.",
    "home.globalCommunity": "Global Community",
    "home.globalCommunityDesc": "Connect with fantasy football enthusiasts worldwide. Share strategies, discuss players, and build lasting friendships.",
    "home.howItWorks": "How It Works",
    "home.howItWorksDesc": "Get started in just a few simple steps and begin your fantasy football journey.",
    "home.createAccount": "Create Account",
    "home.createAccountDesc": "Sign up for free and set up your profile. It takes less than 2 minutes to get started.",
    "home.joinOrCreateLeague": "Join or Create League",
    "home.joinOrCreateLeagueDesc": "Browse existing leagues or create your own. Invite friends and set up your draft preferences.",
    "home.draftAndCompete": "Draft & Compete",
    "home.draftAndCompeteDesc": "Participate in live drafts, manage your team, and compete for the championship title.",
    "home.readyToStart": "Ready to Start Drafting?",
    "home.joinThousands": "Join thousands of fantasy football managers who trust Draft Manager for their leagues.",
    "home.startFreeTrial": "Start Free Trial",
    
    // Auth
    "auth.login": "Login",
    "auth.register": "Register",
    "auth.logout": "Logout",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.name": "Name",
    "auth.confirmPassword": "Confirm Password",
    "auth.forgotPassword": "Forgot Password?",
    "auth.rememberMe": "Remember Me",
    "auth.createAccount": "Create Account",
    "auth.alreadyHaveAccount": "Already have an account?",
    "auth.dontHaveAccount": "Don't have an account?",
    "auth.signIn": "Sign In",
    "auth.signUp": "Sign Up",
    "auth.welcomeBack": "Welcome Back",
    "auth.joinDraftManager": "Join Draft Manager and start your fantasy football journey",
    "auth.passwordMinLength": "Password must be at least 8 characters long",
    "auth.agreeToTerms": "I agree to the",
    "auth.termsOfService": "Terms of Service",
    "auth.and": "and",
    "auth.privacyPolicy": "Privacy Policy",
    "auth.invalidCredentials": "Invalid credentials",
    "auth.emailInUse": "Email is already in use",
    "auth.registrationFailed": "Registration failed",
    "auth.loginFailed": "Login failed",
    "auth.nameOptional": "Name (optional)",
    "auth.enterName": "Enter your name",
    "auth.enterEmail": "Enter your email",
    "auth.createPassword": "Create a password",
    "auth.pleaseAgreeToTerms": "You must agree to Terms of Service and Privacy Policy",
    "auth.enterValidEmail": "Enter a valid email address",
    "auth.loginToAccount": "Login to your Draft Manager account",
    "auth.signingIn": "Signing in...",
    "auth.creatingAccount": "Creating account...",
    
    // Dashboard
    "dashboard.managerHub": "Manager Hub",
    "dashboard.welcomeBack": "Welcome back",
    "dashboard.wins": "Wins",
    "dashboard.activeLeagues": "Active Leagues",
    "dashboard.totalLeagues": "Total Leagues",
    "dashboard.winRate": "Win Rate",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.jumpIntoAction": "Jump into the action",
    "dashboard.myLeagues": "My Leagues",
    "dashboard.findLeagues": "Find Leagues",
    "dashboard.createLeague": "Create League",
    "dashboard.leaderboard": "Leaderboard",
    "dashboard.victoryInPremierLeague": "Victory in Premier League Championship",
    "dashboard.draftedMessi": "Drafted Messi in Fantasy League",
    "dashboard.joinedChampionsLeague": "Joined Champions League",
    "dashboard.unlockedDraftMaster": "Unlocked 'Draft Master' achievement",
    "dashboard.championsLeagueDraft": "Champions League Draft",
    "dashboard.premierLeagueMatchDay": "Premier League Match Day",
    "dashboard.transferWindowOpens": "Transfer Window Opens",
    "dashboard.tomorrow": "Tomorrow",
    "dashboard.friday": "Friday",
    "dashboard.nextMonday": "Next Monday",
    "dashboard.hoursAgo": "hours ago",
    "dashboard.daysAgo": "days ago",
    "dashboard.weekAgo": "week ago",
    
    // Leagues
    "leagues.myCompetitions": "My Competitions",
    "leagues.manageLeagues": "Manage your leagues and track your progress",
    "leagues.totalLeagues": "Total Leagues",
    "leagues.active": "Active",
    "leagues.upcomingDrafts": "Upcoming Drafts",
    "leagues.totalWins": "Total Wins",
    "leagues.myLeagues": "My Leagues",
    "leagues.createNewLeague": "Create New League",
    "leagues.noLeaguesYet": "No Leagues Yet",
    "leagues.createFirstLeague": "Create your first league or join an existing one to get started.",
    "leagues.createYourFirstLeague": "Create Your First League",
    "leagues.teams": "Teams",
    "leagues.method": "Method",
    "leagues.deadline": "Deadline",
    "leagues.top3": "Top 3",
    "leagues.nextEvent": "Next Event",
    "leagues.viewDetails": "View Details",
    "leagues.joinLeague": "Join League",
    "leagues.leaveLeague": "Leave League",
    "leagues.createTeam": "Create Team",
    "leagues.draftDay": "Draft Day",
    "leagues.draftBegins": "Draft Begins",
    "leagues.matchDay": "Match Day",
    "leagues.finalDraftPreparation": "Final draft preparation",
    "leagues.liveDraftSession": "Live draft session",
    "leagues.tomorrow": "Tomorrow",
    "leagues.today": "Today",
    "leagues.friday": "Friday",
    
    // Browse Leagues
    "browseLeagues.title": "League Scouting",
    "browseLeagues.subtitle": "Discover and join the best competitions",
    "browseLeagues.availableLeagues": "Available Leagues",
    "browseLeagues.scoutLeagues": "Scout leagues by name or description...",
    "browseLeagues.filterByStatus": "Filter by Status",
    "browseLeagues.sortByPopularity": "Sort by Popularity",
    "browseLeagues.noLeaguesDiscovered": "No Leagues Discovered",
    "browseLeagues.noLeaguesMatch": "No leagues match your scouting criteria for",
    "browseLeagues.noPublicLeagues": "No public leagues are available for scouting at the moment.",
    "browseLeagues.clearSearch": "Clear Search",
    "browseLeagues.scoutedLeagues": "Scouted Leagues",
    "browseLeagues.clickToJoin": "Click on a league to join the competition",
    "browseLeagues.scoutingLeagues": "Scouting leagues...",
    "browseLeagues.findingBestDraft": "Finding the best draft opportunities for you",
    
    // 404 Not Found
    "notFound.pageNotFound": "Page not found",
    "notFound.pageNotFoundDesc": "The page you're looking for doesn't exist or has been moved.",
    "notFound.goHome": "Go Home",
    "notFound.goBack": "Go Back",
    
    // Navigation
    "navigation.dashboard": "Dashboard",
    "navigation.leagues": "Leagues",
    "navigation.teams": "Teams",
    "navigation.browseLeagues": "Browse Leagues",
    "navigation.account": "Account",
    "navigation.profile": "Profile",
    "navigation.settings": "Settings",
    "navigation.help": "Help",
    "navigation.about": "About",
    "navigation.managerHub": "Manager Hub",
    "navigation.myLeagues": "My Leagues",
    "navigation.scoutLeagues": "Scout Leagues",
    "navigation.createLeague": "Create League",
    "navigation.leaderboard": "Leaderboard",
    "navigation.competitions": "Competitions",
    "navigation.management": "Management",
    
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.welcome": "Welcome Back",
    "dashboard.overview": "Overview",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.stats": "Statistics",
    "dashboard.matches": "Matches",
    "dashboard.wins": "Wins",
    "dashboard.losses": "Losses",
    "dashboard.winRate": "Win Rate",
    "dashboard.points": "Points",
    "dashboard.rank": "Rank",
    "dashboard.level": "Level",
    "dashboard.experience": "Experience",
    "dashboard.nextLevel": "Next Level",
    "dashboard.totalMatches": "Total Matches",
    "dashboard.careerWinRate": "Career Win Rate",
    
    // Leagues
    "leagues.title": "Leagues",
    "leagues.myLeagues": "My Leagues",
    "leagues.browseLeagues": "Browse Leagues",
    "leagues.createLeague": "Create League",
    "leagues.joinLeague": "Join League",
    "leagues.leagueName": "League Name",
    "leagues.leagueDescription": "League Description",
    "leagues.maxPlayers": "Max Players",
    "leagues.entryFee": "Entry Fee",
    "leagues.prizePool": "Prize Pool",
    "leagues.startDate": "Start Date",
    "leagues.endDate": "End Date",
    "leagues.status": "Status",
    "leagues.active": "Active",
    "leagues.completed": "Completed",
    "leagues.upcoming": "Upcoming",
    "leagues.players": "Players",
    "leagues.owner": "Owner",
    "leagues.created": "Created",
    "leagues.joined": "Joined",
    "leagues.leave": "Leave",
    "leagues.viewDetails": "View Details",
    "leagues.noLeagues": "No leagues found",
    "leagues.createFirstLeague": "Create your first league",
    "leagues.joinFirstLeague": "Join your first league",
    
    // Teams
    "teams.title": "Teams",
    "teams.myTeam": "My Team",
    "teams.teamName": "Team Name",
    "teams.teamDescription": "Team Description",
    "teams.formation": "Formation",
    "teams.captain": "Captain",
    "teams.viceCaptain": "Vice Captain",
    "teams.players": "Players",
    "teams.budget": "Budget",
    "teams.remainingBudget": "Remaining Budget",
    "teams.totalValue": "Total Value",
    "teams.avgRating": "Average Rating",
    "teams.chemistry": "Chemistry",
    "teams.tactics": "Tactics",
    "teams.defensive": "Defensive",
    "teams.offensive": "Offensive",
    "teams.balanced": "Balanced",
    "teams.aggressive": "Aggressive",
    "teams.conservative": "Conservative",
    
    // Account
    "account.title": "Account",
    "account.profile": "Profile",
    "account.personalInfo": "Personal Information",
    "account.managerInfo": "Manager Information",
    "account.security": "Security",
    "account.preferences": "Preferences",
    "account.language": "Language",
    "account.selectLanguage": "Select Language",
    "account.danish": "Danish",
    "account.english": "English",
    "account.theme": "Theme",
    "account.light": "Light",
    "account.dark": "Dark",
    "account.system": "System",
    "account.notifications": "Notifications",
    "account.emailNotifications": "Email Notifications",
    "account.pushNotifications": "Push Notifications",
    "account.changePassword": "Change Password",
    "account.currentPassword": "Current Password",
    "account.newPassword": "New Password",
    "account.confirmNewPassword": "Confirm New Password",
    "account.updateProfile": "Update Profile",
    "account.updatePassword": "Update Password",
    "account.deleteAccount": "Delete Account",
    "account.profileUpdated": "Profile Updated",
    "account.passwordUpdated": "Password Updated",
    "account.accountDeleted": "Account Deleted",
    "account.updatePersonalInfo": "Update your personal information and contact details",
    "account.updatePasswordSecure": "Update your password to keep your account secure",
    "account.enterCurrentPassword": "Enter your current password",
    "account.enterNewPassword": "Enter your new password",
    "account.confirmNewPassword": "Confirm your new password",
    "account.updating": "Updating...",
    "account.gameDataManagement": "Game Data Management",
    "account.resetGameData": "Reset game data and populate with sample leagues for testing",
    "account.warningResetData": "Warning: This will reset all game data",
    "account.resetDataDescription": "This will delete all current leagues, teams, and manager progress, then populate the game with sample competitions for testing.",
    "account.resettingGameData": "Resetting Game Data...",
    "account.resetGameDataLoadSample": "Reset Game Data & Load Sample Leagues",
    "account.managerProfile": "Manager Profile",
    "account.manageCareer": "Manage your career and account settings",
    "account.careerWinRate": "Career Win Rate",
    "account.levelRank": "Level {level} - {rank}",
    "account.achievements": "Achievements",
    "account.careerMilestones": "Your career milestones and accomplishments",
    "account.firstVictory": "First Victory",
    "account.winFirstMatch": "Win your first league match",
    "account.draftMaster": "Draft Master",
    "account.completeDrafts": "Complete 10 successful drafts",
    "account.leagueChampion": "League Champion",
    "account.winChampionship": "Win a league championship",
    "account.perfectSeason": "Perfect Season",
    "account.winAllMatches": "Win all matches in a season",
    "account.wins": "Wins",
    "account.losses": "Losses",
    "account.totalMatches": "Total Matches",
    "account.experience": "Experience",
    "account.level": "Level",
    "account.enterName": "Enter your name",
    "account.enterEmail": "Enter your email",
    "account.noChangesToSave": "No changes to save",
    "account.profileUpdatedSuccess": "Profile updated successfully!",
    "account.passwordUpdatedSuccess": "Password updated successfully!",
    "account.newPasswordsDoNotMatch": "New passwords do not match",
    "account.passwordTooShort": "New password must be at least 8 characters long",
    "account.databaseSeededSuccess": "Database seeded successfully! You can now browse leagues and see dummy data.",
    "account.failedToSeedDatabase": "Failed to seed database",
    "account.failedToUpdateProfile": "Failed to update profile",
    "account.failedToUpdatePassword": "Failed to update password",
    
    // Errors
    "errors.generic": "An error occurred",
    "errors.network": "Network error",
    "errors.unauthorized": "Unauthorized",
    "errors.forbidden": "Forbidden",
    "errors.notFound": "Not found",
    "errors.serverError": "Server error",
    "errors.validation": "Validation error",
    "errors.required": "This field is required",
    "errors.invalidEmail": "Invalid email address",
    "errors.passwordTooShort": "Password is too short",
    "errors.passwordsDoNotMatch": "Passwords do not match",
    "errors.userNotFound": "User not found",
    "errors.emailAlreadyExists": "Email already exists",
    "errors.invalidCredentials": "Invalid credentials",
    "errors.accountLocked": "Account is locked",
    "errors.accountDisabled": "Account is disabled",
    "errors.tokenExpired": "Token has expired",
    "errors.tokenInvalid": "Token is invalid",
    
    // Success
    "success.profileUpdated": "Profile updated successfully",
    "success.passwordChanged": "Password changed successfully",
    "success.accountCreated": "Account created successfully",
    "success.loggedIn": "Logged in successfully",
    "success.loggedOut": "Logged out successfully",
    "success.leagueCreated": "League created successfully",
    "success.leagueJoined": "Joined league successfully",
    "success.teamUpdated": "Team updated successfully",
    "success.dataReset": "Data reset successfully"
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("da");
  const [isLoaded, setIsLoaded] = useState(false);

  // Load language from localStorage on mount
  useEffect(() => {
    if (typeof window !== "undefined") {
      const savedLanguage = localStorage.getItem("language") as Language;
      if (savedLanguage && (savedLanguage === "da" || savedLanguage === "en")) {
        setLanguage(savedLanguage);
      }
      setIsLoaded(true);
    }
  }, []);

  // Save language to localStorage when it changes
  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    if (typeof window !== "undefined") {
      localStorage.setItem("language", lang);
    }
  };

  // Translation function
  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  // Don't render until language is loaded to avoid hydration mismatch
  if (!isLoaded) {
    return <div>{children}</div>;
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
